SOURCE = 'ftp://ftp.vim.org/pub/vim/unix/vim-7.4.tar.bz2'
INSTALL_COMMAND = 'sudo apt-get --assume-yes install'
CONFIG_CMD = ('./configure'
              ' --enable-perlinterp'
              ' --enable-{pversion}interp'
              ' --with-python-config-dir={pconfig_path}'
              ' vi_cv_path_{pversion}={vi_cv_path_python}'
              ' --enable-gpm'
              ' --enable-acl'
              ' --enable-cscope'
              ' --disable-selinux'
              ' --enable-rubyinterp'
              ' --enable-cscope'
              ' --with-features=huge'
              ' --prefix={home}')
